### PR TITLE
Remove WPE patch "include-gstglmemoryegl.h" after it has been merged upstream

### PR DESCRIPTION
**Pull request by scthunderbolt**
See https://github.com/Metrological/WebKitForWayland/commit/0fca12f80d079e968b6667a98685d65cdf04d982

### CODE REVIEW

**Comment by kraj** [comment]
@scthunderbolt  Can you also include the link to upstream commit ?

**Comment by scthunderbolt** [comment]
Sure the upstream is here:

https://github.com/Metrological/WebKitForWayland/commit/0fca12f80d079e968b6667a98685d65cdf04d982

**Comment by kraj** [comment]
the commit shown here is for westeros. Did you rebase the master wrongly. ?

**Comment by scthunderbolt** [comment]
Yes, the second commit shouldn't be there. Trying to fix it now.

**Comment by scthunderbolt** [comment]
Hi Khem,
It should be OK now.
Added a link to the upstream in the Commit msg.
Simon.

**Comment by wouterlucas** [comment]
Thanks! Will merge once we bump WPE, #16e0f WPE still needs this patch.

**Pull request merged**
