### PR TITLE
Fixes with latest master after recipe specific sysroot changes.

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by kraj** [comment]
@wouterlucas can you take a look at it ?

**Comment by wouterlucas** [comment]
Please see my comment from 6 days ago, can you provide feedback on that?

**Comment by kraj** [comment]
I dont see any comment, can you add it again ? or link to it

**Comment by wouterlucas** [comment]
https://github.com/Metrological/meta-metrological/pull/122#discussion_r98055557

Basically, that patch you're applying to WPE. Does it make sense to just add it to the WPE repo instead of maintaining it in meta-metrological? Would like to understand why we would only patch this here.

**Comment by kraj** [comment]
I think eventually it should go into WPE, but I wanted more folks than me try it out first thats why applying it for OE only.

**Comment by wouterlucas** [comment]
OK - will merge and we'll move it up after you give it a whirl.

**Pull request merged**
