### PR TITLE
Fixes to build with latest oe master

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by wouterlucas** [comment]
@kraj I just rebuild rpi3 with the latest bumps and it links fine for me. Can you cross check?

**Comment by kraj** [comment]
@wouterlucas it does not work for me. I also enable security flags in poky. can you add

require conf/distro/include/security_flags.inc

in your local.conf ?

and use latest master of poky. What revision of poky are you on ?

**Comment by wouterlucas** [comment]
I'm using @armcc's meta layers, which I believe are on Jethro. Is this an issue that surfaces with a more recent GCC?

**Comment by kraj** [comment]
ah that speaks of it then, I think you should move to using upstream master as well. This issue will hit you when you have gcc6. These patches just make it backward compatible to older gcc.

**Comment by kraj** [comment]
@wouterlucas this changeset should not break backward compatibility its just trying to be explicit about the ABI so the newer compilers dont mess it us. For older toolsets it should just mean nop.

**Pull request merged**
